tbb_version: 2020.3

---

build_all:
  name: Build tbb - All
  dependencies:
    - .yamato/build.yml#build_windows
    - .yamato/build.yml#build_mac
    - .yamato/build.yml#build_linux

build_windows:
    name: Build tbb - Windows
    agent:
        type: Unity::VM
        image: usd-foundation/usd-build-win10:v0.1.2-1255774
        flavor: b1.small
    commands:
        - bee artifacts/for-stevedore/tbb-win-x64.7z
        #- bee artifacts/for-stevedore/tbb-win-x64-dbg.7z
        #- bee artifacts/for-stevedore/tbb-win-arm64.7z
        #- bee artifacts/for-stevedore/tbb-win-arm64-dbg.7z
        - 7z x artifacts\for-stevedore\tbb-win-x64.7z -o.\tbb-win-x64-sgn
        - brick_source: git@github.cds.internal.unity3d.com:unity/batch.cds.ci.code-signing.git@v1.0.8
          variables:
              AZURE_CERTIFICATE: ov-unity-technologies-aps
              FILES: tbb-win-x64-sgn\bin\tbb.dll tbb-win-x64-sgn\bin\tbbmalloc.dll tbb-win-x64-sgn\bin\tbbmalloc_proxy.dll
        - 7z a artifacts\for-stevedore\tbb-win-x64-sgn.7z .\tbb-win-x64-sgn\* -aoa
        - del artifacts\for-stevedore\tbb-win-x64.7z
        - curl -sSo StevedoreUpload.exe "%STEVEDORE_UPLOAD_TOOL_WINDOWS_X64_URL%"
        - StevedoreUpload.exe --repo=testing --version="{{tbb_version}}" artifacts/for-stevedore/*
    artifacts:
        artifacts:
            paths:
                - artifacts/for-stevedore/*

build_mac:
    name: Build tbb - Mac
    agent:
        type: Unity::VM::osx
        image: usd-foundation/usd-build-macos-10.15:v0.1.0-1221647
        flavor: b1.small
    commands:
        - ./bee artifacts/for-stevedore/tbb-mac-x64.7z
        - ./bee artifacts/for-stevedore/tbb-mac-x64-dbg.7z
        - ./bee artifacts/for-stevedore/tbb-mac-arm64.7z
        - ./bee artifacts/for-stevedore/tbb-mac-arm64-dbg.7z
        - curl -sSo StevedoreUpload "$STEVEDORE_UPLOAD_TOOL_MAC_X64_URL"
        - chmod +x StevedoreUpload
        - ./StevedoreUpload --repo=testing --version="{{tbb_version}}" artifacts/for-stevedore/*
    artifacts:
        artifacts:
            paths:
                - artifacts/for-stevedore/*

build_linux:
    name: Build tbb - Linux
    agent:
        type: Unity::VM
        image: usd-foundation/usd-build-ubuntu-18.04:v0.1.0-1221777
        flavor: b1.small
    commands:
        - ./bee artifacts/for-stevedore/tbb-linux-x64.7z
        - ./bee artifacts/for-stevedore/tbb-linux-x64-dbg.7z
        - curl -sSo StevedoreUpload "$STEVEDORE_UPLOAD_TOOL_LINUX_X64_URL"
        - chmod +x StevedoreUpload
        - ./StevedoreUpload --repo=testing --version="{{tbb_version}}" artifacts/for-stevedore/*
    artifacts:
        artifacts:
            paths:
                - artifacts/for-stevedore/*
